import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import {
  Sale,
  ProductionBatch,
  FinishedGoodsInventory,
  Customer,
  Purchase,
  Supplier,
} from '../types/database';
import { formatCurrency, formatDate } from './utils';
import { getCompanyDocumentBranding, CompanyDocumentBranding } from './branding';

/**
 * Standardized document branding header renderer for jsPDF documents
 */
function renderPdfDocumentHeader(
  doc: jsPDF,
  branding: CompanyDocumentBranding,
  documentTitle: string,
  docNumber?: string,
  docDate?: string
): number {
  // Top Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 42, 'F');

  // If Logo exists and is a base64 / valid image data url, try drawing it
  let textStartX = 15;
  if (branding.logoUrl && (branding.logoUrl.startsWith('data:image/') || branding.logoUrl.startsWith('http'))) {
    try {
      const isPng = branding.logoUrl.includes('png');
      const format = isPng ? 'PNG' : 'JPEG';
      doc.addImage(branding.logoUrl, format, 12, 8, 22, 22);
      textStartX = 38;
    } catch {
      // Fallback cleanly to text header without throwing error
      textStartX = 15;
    }
  }

  // Primary Company Legal Name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const upperCompanyName = (branding.companyName || 'Company Name').toUpperCase();
  doc.text(upperCompanyName.slice(0, 38), textStartX, 16);

  // Address & Contacts
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(203, 213, 225); // slate-300
  const addressLine = `${branding.address}${branding.country ? ` • ${branding.country}` : ''}`;
  doc.text(addressLine.slice(0, 75), textStartX, 22);

  const contactLine = `Tel: ${branding.phone}  |  Email: ${branding.email}`;
  doc.text(contactLine.slice(0, 75), textStartX, 28);

  const taxAndPlantLine = `Tax ID: ${branding.taxId}  |  Plant: ${branding.plantName}`;
  doc.text(taxAndPlantLine.slice(0, 75), textStartX, 34);

  // Document Type & Metadata Banner (Right Aligned)
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(56, 189, 248); // sky-400
  doc.text(documentTitle.toUpperCase(), 195, 17, { align: 'right' });

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(241, 245, 249);
  if (docNumber) {
    doc.text(`Doc #: ${docNumber}`, 195, 24, { align: 'right' });
  }
  if (docDate) {
    doc.text(`Date: ${formatDate(docDate)}`, 195, 30, { align: 'right' });
  }

  return 48; // Return start Y for content
}

/**
 * Standardized document branding footer renderer for jsPDF documents
 */
function renderPdfDocumentFooter(
  doc: jsPDF,
  branding: CompanyDocumentBranding,
  footerY: number = 265
) {
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(15, footerY, 195, footerY);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Thank you for your business.', 15, footerY + 6);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `${branding.companyName} • Tel: ${branding.phone} • Email: ${branding.email}`,
    15,
    footerY + 11
  );

  // Small secondary software indicator
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by H2O Water Management System', 195, footerY + 11, { align: 'right' });
}

/**
 * Enhanced Excel export that replaces generic/H2O filenames with the customer's legal company name
 */
export function exportToExcel(data: any[], fileName: string, sheetName: string = 'Data') {
  try {
    const branding = getCompanyDocumentBranding();
    const cleanCompany = (branding.companyName || 'Company')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');

    // Replace generic "H2O_" with client company name
    let resolvedFileName = fileName;
    if (resolvedFileName.startsWith('H2O_')) {
      resolvedFileName = `${cleanCompany}_${resolvedFileName.replace(/^H2O_/, '')}`;
    } else if (!resolvedFileName.includes(cleanCompany)) {
      resolvedFileName = `${cleanCompany}_${resolvedFileName}`;
    }

    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    XLSX.writeFile(workbook, `${resolvedFileName}_${new Date().toISOString().slice(0, 10)}.xlsx`);
  } catch (error) {
    console.error('Error exporting to Excel:', error);
  }
}

/**
 * Enhanced CSV export that prefixes filenames with the customer's legal company name
 */
export function exportToCSV(data: any[], fileName: string) {
  try {
    const branding = getCompanyDocumentBranding();
    const cleanCompany = (branding.companyName || 'Company')
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');

    let resolvedFileName = fileName;
    if (resolvedFileName.startsWith('H2O_')) {
      resolvedFileName = `${cleanCompany}_${resolvedFileName.replace(/^H2O_/, '')}`;
    } else if (!resolvedFileName.includes(cleanCompany)) {
      resolvedFileName = `${cleanCompany}_${resolvedFileName}`;
    }

    const worksheet = XLSX.utils.json_to_sheet(data);
    const csvOutput = XLSX.utils.sheet_to_csv(worksheet);
    const blob = new Blob([csvOutput], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${resolvedFileName}_${new Date().toISOString().slice(0, 10)}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error('Error exporting to CSV:', error);
  }
}

/**
 * Generates customer-branded Sales Invoice, Receipt, or Delivery Note PDF
 */
export function generateInvoicePDF(
  sale: Sale,
  customer?: Customer,
  type: 'Invoice' | 'Receipt' | 'Delivery Note' = 'Invoice'
) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    type,
    sale.invoice_number,
    sale.sale_date
  );

  // Bill To / Details Section
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('CUSTOMER / BILL TO:', 15, startY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Name: ${customer?.name || sale.customer_name || 'Walk-in Customer'}`, 15, startY + 12);
  doc.text(`Type: ${customer?.type || sale.type || 'Retail'}`, 15, startY + 17);
  doc.text(`Phone: ${customer?.phone || 'N/A'}`, 15, startY + 22);
  doc.text(`Address: ${customer?.address || 'N/A'}`, 15, startY + 27);

  // Transaction Details Box
  doc.setFont('helvetica', 'bold');
  doc.text('TRANSACTION DETAILS:', 120, startY + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`Payment Status: ${sale.payment_status}`, 120, startY + 12);
  doc.text(`Payment Method: ${sale.payment_method}`, 120, startY + 17);
  doc.text(`Due Date: ${formatDate(sale.due_date) || 'Immediate'}`, 120, startY + 22);
  doc.text(`Sales Rep: ${sale.salesperson_name || 'HQ Sales'}`, 120, startY + 27);

  // Table Headers
  const tableStartY = startY + 36;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, tableStartY, 180, 8, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.rect(15, tableStartY, 180, 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  doc.text('#', 18, tableStartY + 5.5);
  doc.text('Product Description / Size', 30, tableStartY + 5.5);
  doc.text('Quantity', 115, tableStartY + 5.5, { align: 'right' });
  doc.text('Unit Price', 150, tableStartY + 5.5, { align: 'right' });
  doc.text('Total', 190, tableStartY + 5.5, { align: 'right' });

  // Table Rows
  let currentY = tableStartY + 8;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);

  sale.items.forEach((item, index) => {
    currentY += 8;
    doc.text(`${index + 1}`, 18, currentY - 2);
    doc.text(`Purified Bottled Water - ${item.bottle_size}`, 30, currentY - 2);
    doc.text(`${item.quantity.toLocaleString()}`, 115, currentY - 2, { align: 'right' });
    doc.text(`${formatCurrency(item.unit_price)}`, 150, currentY - 2, { align: 'right' });
    doc.text(`${formatCurrency(item.total_price)}`, 190, currentY - 2, { align: 'right' });
    doc.line(15, currentY, 195, currentY);
  });

  // Summary section
  const summaryY = currentY + 10;
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal:', 140, summaryY);
  doc.text(`${formatCurrency(sale.subtotal)}`, 190, summaryY, { align: 'right' });

  if (sale.discount > 0) {
    doc.text('Discount:', 140, summaryY + 5);
    doc.text(`-${formatCurrency(sale.discount)}`, 190, summaryY + 5, { align: 'right' });
  }

  if (sale.tax > 0) {
    doc.text('Tax (VAT):', 140, summaryY + 10);
    doc.text(`+${formatCurrency(sale.tax)}`, 190, summaryY + 10, { align: 'right' });
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setFillColor(240, 249, 255);
  doc.rect(135, summaryY + 13, 60, 8, 'F');
  doc.setTextColor(2, 132, 199);
  doc.text('Total Amount:', 140, summaryY + 18.5);
  doc.text(`${formatCurrency(sale.total_amount)}`, 190, summaryY + 18.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Amount Paid: ${formatCurrency(sale.amount_paid)}`, 140, summaryY + 26);
  doc.text(`Balance Due: ${formatCurrency(sale.total_amount - sale.amount_paid)}`, 140, summaryY + 31);

  // Signatures
  const sigY = 245;
  doc.text('_____________________________', 25, sigY);
  doc.text('Authorized Signature / Dispatcher', 25, sigY + 4);

  doc.text('_____________________________', 140, sigY);
  doc.text('Customer Received Signature & Date', 140, sigY + 4);

  // Footer with customer company branding
  renderPdfDocumentFooter(doc, branding, 258);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_${type}_${sale.invoice_number}.pdf`);
}

/**
 * Generates customer-branded Production Audit Report PDF
 */
export function generateProductionReportPDF(
  batches: ProductionBatch[],
  inventory: FinishedGoodsInventory[]
) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    'PRODUCTION AUDIT',
    `AUDIT-${new Date().toISOString().slice(0, 10)}`,
    new Date().toISOString()
  );

  // Summary Metrics
  const totalProduced = batches.reduce((acc, b) => acc + b.quantity_produced, 0);
  const totalAccepted = batches.reduce((acc, b) => acc + b.accepted_quantity, 0);
  const totalRejected = batches.reduce((acc, b) => acc + b.rejected_quantity + b.damaged_bottles, 0);
  const avgEfficiency = totalProduced > 0 ? (totalAccepted / totalProduced) * 100 : 0;

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'bold');
  doc.text('PLANT MANUFACTURING PERFORMANCE SUMMARY', 15, startY + 6);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Facility: ${branding.plantName}`, 15, startY + 12);
  doc.text(`Total Batches Logged: ${batches.length}`, 15, startY + 17);
  doc.text(`Total Produced Units: ${totalProduced.toLocaleString()}`, 15, startY + 22);
  doc.text(`Total Accepted (Good Quality): ${totalAccepted.toLocaleString()}`, 90, startY + 17);
  doc.text(`Total Scrap / Waste: ${totalRejected.toLocaleString()}`, 90, startY + 22);
  doc.text(`Plant Line Yield: ${avgEfficiency.toFixed(2)}%`, 150, startY + 17);

  // Table
  let y = startY + 32;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, 180, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('Batch #', 17, y + 4.5);
  doc.text('Date', 52, y + 4.5);
  doc.text('Size', 70, y + 4.5);
  doc.text('Machine', 85, y + 4.5);
  doc.text('Produced', 125, y + 4.5, { align: 'right' });
  doc.text('Accepted', 150, y + 4.5, { align: 'right' });
  doc.text('Waste %', 172, y + 4.5, { align: 'right' });
  doc.text('Cost/Unit', 192, y + 4.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  batches.slice(0, 22).forEach((b) => {
    y += 7;
    doc.text(b.batch_number, 17, y + 4.5);
    doc.text(formatDate(b.production_date), 52, y + 4.5);
    doc.text(b.bottle_size, 70, y + 4.5);
    doc.text((b.machine_used || 'RO Line').slice(0, 18), 85, y + 4.5);
    doc.text(b.quantity_produced.toLocaleString(), 125, y + 4.5, { align: 'right' });
    doc.text(b.accepted_quantity.toLocaleString(), 150, y + 4.5, { align: 'right' });
    doc.text(`${b.waste_percent}%`, 172, y + 4.5, { align: 'right' });
    doc.text(formatCurrency(b.cost_per_bottle || 0.18), 192, y + 4.5, { align: 'right' });
    doc.line(15, y + 6, 195, y + 6);
  });

  renderPdfDocumentFooter(doc, branding, 260);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_Production_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Generates customer-branded Purchase Order PDF
 */
export function generatePurchaseOrderPDF(purchase: Purchase, supplier?: Supplier) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    'PURCHASE ORDER',
    purchase.po_number,
    purchase.order_date
  );

  // Vendor Details
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('VENDOR / SUPPLIER:', 15, startY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Supplier: ${supplier?.name || purchase.supplier_name || 'Vendor'}`, 15, startY + 12);
  doc.text(`Phone: ${supplier?.phone || 'N/A'}`, 15, startY + 17);
  doc.text(`Email: ${supplier?.email || 'N/A'}`, 15, startY + 22);
  doc.text(`Address: ${supplier?.address || 'N/A'}`, 15, startY + 27);

  // PO Meta
  doc.setFont('helvetica', 'bold');
  doc.text('ORDER SPECIFICATIONS:', 120, startY + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`PO Status: ${purchase.status}`, 120, startY + 12);
  doc.text(`Payment Status: ${purchase.payment_status || 'Pending'}`, 120, startY + 17);
  doc.text(`Expected Delivery: ${formatDate(purchase.expected_delivery_date)}`, 120, startY + 22);
  doc.text(`Delivery Facility: ${purchase.branch_name || branding.plantName}`, 120, startY + 27);

  // Table
  const tableStartY = startY + 36;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, tableStartY, 180, 8, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.rect(15, tableStartY, 180, 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  doc.text('#', 18, tableStartY + 5.5);
  doc.text('Item Description / Material', 30, tableStartY + 5.5);
  doc.text('Quantity', 115, tableStartY + 5.5, { align: 'right' });
  doc.text('Unit Cost', 150, tableStartY + 5.5, { align: 'right' });
  doc.text('Total Cost', 190, tableStartY + 5.5, { align: 'right' });

  let currentY = tableStartY + 8;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);

  (purchase.items || []).forEach((item, index) => {
    currentY += 8;
    doc.text(`${index + 1}`, 18, currentY - 2);
    const itemName = (item as any).raw_material_name || (item as any).item_name || 'Raw Material Item';
    const itemUnit = (item as any).unit || 'units';
    doc.text(`${itemName}`, 30, currentY - 2);
    doc.text(`${item.quantity.toLocaleString()} ${itemUnit}`, 115, currentY - 2, {
      align: 'right',
    });
    doc.text(`${formatCurrency(item.unit_cost)}`, 150, currentY - 2, { align: 'right' });
    doc.text(`${formatCurrency(item.total_cost)}`, 190, currentY - 2, { align: 'right' });
    doc.line(15, currentY, 195, currentY);
  });

  // Summary
  const summaryY = currentY + 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setFillColor(240, 249, 255);
  doc.rect(135, summaryY, 60, 8, 'F');
  doc.setTextColor(2, 132, 199);
  doc.text('Total Order Amount:', 140, summaryY + 5.5);
  doc.text(`${formatCurrency(purchase.total_amount)}`, 190, summaryY + 5.5, { align: 'right' });

  // Signatures
  const sigY = 245;
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text('_____________________________', 25, sigY);
  doc.text('Procurement Manager Authorization', 25, sigY + 4);

  doc.text('_____________________________', 140, sigY);
  doc.text('Supplier Acceptance Signature & Date', 140, sigY + 4);

  renderPdfDocumentFooter(doc, branding, 258);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_PO_${purchase.po_number}.pdf`);
}

/**
 * Generates customer-branded Financial Statement PDF (Profit & Loss, Balance Sheet, Trial Balance)
 */
export function generateFinancialReportPDF(
  statementTitle: string,
  period: string,
  sections: Array<{
    title: string;
    rows: Array<{ label: string; amount: number; isBold?: boolean }>;
    totalLabel?: string;
    totalAmount?: number;
  }>
) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    statementTitle,
    `FIN-${new Date().toISOString().slice(0, 10)}`,
    new Date().toISOString()
  );

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`ACCOUNTING PERIOD: ${period.toUpperCase()}`, 15, startY + 6);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Operating Currency: ${branding.currency} (${branding.currencySymbol})`, 15, startY + 11);

  let currentY = startY + 18;

  sections.forEach((sec) => {
    // Section Header
    doc.setFillColor(241, 245, 249);
    doc.rect(15, currentY, 180, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(sec.title.toUpperCase(), 18, currentY + 4.5);
    currentY += 8;

    // Rows
    sec.rows.forEach((r) => {
      doc.setFont('helvetica', r.isBold ? 'bold' : 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(r.isBold ? 15 : 71, r.isBold ? 23 : 85, r.isBold ? 42 : 105);
      doc.text(r.label, 20, currentY);
      doc.text(formatCurrency(r.amount), 190, currentY, { align: 'right' });
      currentY += 6;
    });

    if (sec.totalLabel && sec.totalAmount !== undefined) {
      doc.setDrawColor(203, 213, 225);
      doc.line(15, currentY - 2, 195, currentY - 2);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(2, 132, 199);
      doc.text(sec.totalLabel, 20, currentY + 3);
      doc.text(formatCurrency(sec.totalAmount), 190, currentY + 3, { align: 'right' });
      currentY += 9;
    } else {
      currentY += 3;
    }
  });

  renderPdfDocumentFooter(doc, branding, 260);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  const safeTitle = statementTitle.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_${safeTitle}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Generates customer-branded Sales Audit Report PDF
 */
export function generateSalesAuditReportPDF(sales: Sale[]) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    'SALES & REVENUE REPORT',
    `SALES-${new Date().toISOString().slice(0, 10)}`,
    new Date().toISOString()
  );

  const totalSalesVal = sales.reduce((acc, s) => acc + s.total_amount, 0);
  const totalPaidVal = sales.reduce((acc, s) => acc + s.amount_paid, 0);
  const totalOutstanding = totalSalesVal - totalPaidVal;

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('COMMERCIAL REVENUE & DISPATCH PERFORMANCE', 15, startY + 6);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Invoices: ${sales.length}`, 15, startY + 12);
  doc.text(`Gross Revenue: ${formatCurrency(totalSalesVal)}`, 15, startY + 17);
  doc.text(`Cash Realized: ${formatCurrency(totalPaidVal)}`, 85, startY + 12);
  doc.text(`Receivables Outstanding: ${formatCurrency(totalOutstanding)}`, 85, startY + 17);

  // Table
  let y = startY + 24;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, 180, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('Invoice #', 17, y + 4.5);
  doc.text('Date', 50, y + 4.5);
  doc.text('Customer', 72, y + 4.5);
  doc.text('Status', 125, y + 4.5);
  doc.text('Total', 160, y + 4.5, { align: 'right' });
  doc.text('Paid', 192, y + 4.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  sales.slice(0, 24).forEach((s) => {
    y += 7;
    doc.text(s.invoice_number, 17, y + 4.5);
    doc.text(formatDate(s.sale_date), 50, y + 4.5);
    doc.text((s.customer_name || 'Retail').slice(0, 24), 72, y + 4.5);
    doc.text(s.payment_status, 125, y + 4.5);
    doc.text(formatCurrency(s.total_amount), 160, y + 4.5, { align: 'right' });
    doc.text(formatCurrency(s.amount_paid), 192, y + 4.5, { align: 'right' });
    doc.line(15, y + 6, 195, y + 6);
  });

  renderPdfDocumentFooter(doc, branding, 260);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_Sales_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Generates customer-branded Operating Expense Report PDF
 */
export function generateExpenseReportPDF(expenses: any[]) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    'OPERATING EXPENSE REPORT',
    `OPEX-${new Date().toISOString().slice(0, 10)}`,
    new Date().toISOString()
  );

  const totalOpex = expenses.reduce((acc, e) => acc + (e.amount || 0), 0);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('OPERATING EXPENDITURE AUDIT VOUCHER', 15, startY + 6);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Expense Items: ${expenses.length}`, 15, startY + 12);
  doc.text(`Aggregate Disbursed Amount: ${formatCurrency(totalOpex)}`, 15, startY + 17);

  let y = startY + 24;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, 180, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('Date', 17, y + 4.5);
  doc.text('Category', 45, y + 4.5);
  doc.text('Description / Payee', 85, y + 4.5);
  doc.text('Amount', 192, y + 4.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  expenses.slice(0, 24).forEach((e) => {
    y += 7;
    doc.text(formatDate(e.date), 17, y + 4.5);
    doc.text((e.category || 'General').slice(0, 18), 45, y + 4.5);
    doc.text(`${e.description || ''} (${e.payee || 'Direct'})`.slice(0, 48), 85, y + 4.5);
    doc.text(formatCurrency(e.amount), 192, y + 4.5, { align: 'right' });
    doc.line(15, y + 6, 195, y + 6);
  });

  renderPdfDocumentFooter(doc, branding, 260);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_Expense_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Generates customer-branded Inventory Health Report PDF
 */
export function generateInventoryReportPDF(inventory: FinishedGoodsInventory[]) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const branding = getCompanyDocumentBranding();
  const startY = renderPdfDocumentHeader(
    doc,
    branding,
    'INVENTORY HEALTH AUDIT',
    `INV-STOCK-${new Date().toISOString().slice(0, 10)}`,
    new Date().toISOString()
  );

  const totalStockUnits = inventory.reduce((acc, i) => acc + (i.current_stock || 0), 0);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('WAREHOUSE STOCK LEVEL & VALUATION', 15, startY + 6);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Warehouse / Facility: ${branding.plantName}`, 15, startY + 12);
  doc.text(`Total Finished Stock Units: ${totalStockUnits.toLocaleString()}`, 15, startY + 17);

  let y = startY + 24;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, 180, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('SKU / Bottle Size', 17, y + 4.5);
  doc.text('Warehouse Location', 75, y + 4.5);
  doc.text('Current Stock', 130, y + 4.5, { align: 'right' });
  doc.text('Min Safety', 160, y + 4.5, { align: 'right' });
  doc.text('Stock Status', 192, y + 4.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  inventory.forEach((i) => {
    y += 7;
    doc.text(i.bottle_size, 17, y + 4.5);
    doc.text(i.location || 'Central Depot', 75, y + 4.5);
    doc.text(i.current_stock.toLocaleString(), 130, y + 4.5, { align: 'right' });
    doc.text(i.min_stock.toLocaleString(), 160, y + 4.5, { align: 'right' });
    const isLow = i.current_stock <= i.min_stock;
    doc.text(isLow ? 'REORDER' : 'OPTIMAL', 192, y + 4.5, { align: 'right' });
    doc.line(15, y + 6, 195, y + 6);
  });

  renderPdfDocumentFooter(doc, branding, 260);

  const cleanCompany = branding.companyName.replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${cleanCompany}_Inventory_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}

